#!/usr/bin/python3

#       _           _      _             _     _
#      | |_   _ ___| |_   / \   _ __ ___| |__ (_)
#   _  | | | | / __| __| / _ \ | '__/ __| '_ \| |
#  | |_| | |_| \__ \ |_ / ___ \| | | (__| | | | |
#   \___/ \__,_|___/\__/_/   \_\_|  \___|_| |_|_|
#
#  Copyright 2017 Łukasz "JustArchi" Domeradzki
#  Contact: JustArchi@JustArchi.net
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

import argparse
import sys

from mutagen.oggopus import OggOpus

parser = argparse.ArgumentParser()
parser.add_argument('-c', '--comment')
parser.add_argument('-p', '--performer')
parser.add_argument('-tn', '--tracknumber', type=int)
parser.add_argument('-tt', '--tracktotal', type=int)
parser.add_argument('file')

args = parser.parse_args()

audio = OggOpus(args.file)

if args.comment is not None:
	audio["comment"] = args.comment

if args.performer is not None:
	audio["performer"] = args.performer

if args.tracknumber is not None:
	audio["tracknumber"] = str(args.tracknumber)

if args.tracktotal is not None:
	audio["tracktotal"] = str(args.tracktotal)

audio.save()
